[package]
name = "raphiis-desktop-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
global-hotkey = "0.2.1"
tao = "0.20.0"
windows = { version = "0.44.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
] }
winvd = "0.0.30"
